Add Tasks 1-7 (from the initial requirements, styles not fully implemented)
arty987/vue-perfect-to-do pull request #1
Opened 2024-08-23 09:25 UTC by arty987

2024-08-23 12:09 UTC, KHarpushkina requested changes
Good project structure, great pull request!

2024-08-23 12:09 UTC, KHarpushkina commented on src/components/atoms/AppInput.vue
> +        this.$store.dispatch("addTask", inputValue);
I think AppInput as an atom is not responsible for this. It should just have some event (e.g. enterClick) and emit the parent event. In this case we will be able to reuse it in different components and perform different actions by pressing Enter, not just 'addTask'

2024-08-23 12:09 UTC, KHarpushkina commented on src/store/mutations.js
> +    },
Could you make it as one mutation and just pass an argument with the new value for the filter?

2024-08-23 12:09 UTC, KHarpushkina commented on src/store/mutations.js
> +    },
Also, I think it makes sense to create some kind of enum (e.g. Object.freeze()) for filter values - 'all', 'active', 'completed'. You can store it in separate file - constants.js

2024-08-23 12:09 UTC, KHarpushkina commented on src/App.vue
> +  <AppContent/>
I think here should be Page, not Template. This would be more consistent with atomic design. A page is the final, fully realized design step. It should be in separate folder - pages. Template should be more like layout, and page is a final view, that users see

2024-08-24 09:26 UTC, arty987 commented on src/components/atoms/AppInput.vue
> +        this.$store.dispatch("addTask", inputValue);
Thank you. Updated the component to emit its events.

2024-08-24 09:28 UTC, arty987 commented on src/store/mutations.js
> +    },
Replaced display mutations with setFilter one. Created the enum for filters.

2024-08-24 09:29 UTC, arty987 commented on src/App.vue
> +  <AppContent/>
Moved AppContent to 'pages' directory.

2024-08-26 10:21 UTC, KHarpushkina approved these changes

2024-08-26 10:21 UTC, KHarpushkina commented on src/components/atoms/AppInput.vue
> +      this.$emit("enter");
Just small note. It is recommended to declare emits - https://vuejs.org/guide/components/events.html#declaring-emitted-events

2024-08-26 11:14 UTC, merged