Add unit tests
arty987/vue-perfect-to-do pull request #3
Opened 2024-08-29 08:31 UTC by arty987

2024-08-29 12:10 UTC, KHarpushkina requested changes
The tests look great 👍

2024-08-29 12:10 UTC, KHarpushkina commented on src/components/atoms/__tests__/AppInput.spec.js
> +        const wrapper = shallowMount(AppInput, {
You don't need to call a shallowMount for each test, just create a const at the top of the file and then use it in all the 'it' blocks

2024-08-29 12:10 UTC, KHarpushkina commented on src/components/atoms/__tests__/AppCheckbox.spec.js
> +        const wrapper = shallowMount(AppCheckbox, {
You can use setProps to change the properties of your component, no need to call shallowMount again

2024-08-30 07:28 UTC, arty987 commented on src/components/atoms/__tests__/AppInput.spec.js
> +        const wrapper = shallowMount(AppInput, {
Replaced multiple shallowMount calls with the constant

2024-08-30 07:28 UTC, arty987 commented on src/components/atoms/__tests__/AppCheckbox.spec.js
> +        const wrapper = shallowMount(AppCheckbox, {
Replaced multiple shallowMount calls with the constant

2024-08-30 13:43 UTC, KHarpushkina approved these changes

2024-08-30 13:44 UTC, merged